on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build project
        run: ./build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: registry.tgozzz.cn
          username: itgo
          password: lyq1999==

      - name: Build Docker image
        run: |
          docker build \
          -t goodsman-web:latest \
          -t goodsman-web:${{ github.sha }} \
          -t itgo/goodsman-web:latest \
          -t registry.tgozzz.cn/itgo/goodsman-web:latest \
          -t registry.tgozzz.cn/itgo/goodsman-web:${{ github.sha }} \
          .
      
      - name: Inspect Docker image
        run: |
          docker image inspect goodsman-web:latest

      - name: Push Docker image
        run: docker push registry.tgozzz.cn/itgo/goodsman-web:latest
