on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: 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

      - name: Build project
        run: ./build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and tag Docker image
        run: |
          docker buildx build --file Dockerfile \
            --tag goodsman-web:latest \
            --tag goodsman-web:${{ github.sha }} \
            .

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.tgozzz.cn
          username: itgo
          password: lyq1999==

      - name: Push Docker image
        run: |
          docker push registry.tgozzz.cn/itgo/goodsman-web